fpath=("/usr/share/zsh/functions/Completion" "/usr/share/zsh/functions" $fpath)
# Custom color prompt setup

reset_color='%f'

# Completion: only once!
fpath=(~/.zsh/zsh-completions/src $fpath)
autoload -Uz compinit && compinit
# Aliases and functions
alias k='kubectl'
alias pip="python3 -m pip"

# History settings
HISTSIZE=100000
SAVEHIST=100000
HISTFILE=~/.zsh_history
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY

# Path, completions, and other sources
source <(tailscale completion zsh)
source "$HOME/dev/bin/aliases.zsh"
source "$HOME/dev/bin/custom_path.zsh"
source "$HOME/dev/bin/constants.zsh"
source "$HOME/dev/bin/functions.zsh"
source "$HOME/dev/bin/colors.zsh"
machine_color=$FG_LIME_GREEN
source "$HOME/dev/bin/autoload_environment.zsh"
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# Prompt (set last)
PROMPT='[ %n @ '"${machine_color}"'%m'"${reset_color}"' ] %1~ > '
bindkey '^U' backward-kill-line
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
setopt COMPLETE_ALIASES
unsetopt CASE_GLOB

fpath+=~/.zfunc; autoload -Uz compinit; compinit

eval "$(uv generate-shell-completion zsh)" 2>/dev/null || true
